[package]
name = "ldr_poc"
version = "0.1.0"
edition = "2024"

[dependencies]
pigpio-sys = "0.1.1"
tokio = {version = "1", features = ["full"]}

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
